services:
  redis:
    image: docker.io/library/redis:8.6.1-alpine
    container_name: redis
    command: redis-server --port ${REDIS_PORT} --loglevel warning --protected-mode no
    ports: 
      - 127.0.0.1:${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped

  concord:
    image: docker.io/library/node:24.14.0-alpine
    container_name: concord
    working_dir: /app
    command: node bootstrap.js
    environment:
      - IS_CONTAINER=true
    depends_on: 
      - redis
    env_file: .env
    ports: 
      - ${API_PORT}:${API_PORT}
    volumes:
      # Named volumes (performance + isolation)
      - concord-yarn:/app/.yarn:Z
      - concord-data:/app/data:Z

      # Bind mounts (you edit on host)
      - ./src:/app/src:Z
      - ./bootstrap.js:/app/bootstrap.js:Z
      - ./nodemon.json:/app/nodemon.json:Z
      - ./package.json:/app/package.json:Z
      - ./podman-compose.yaml:/app/podman-compose.yaml:Z
      - ./tsconfig.json:/app/tsconfig.json:Z
    restart: unless-stopped

  caddy:
    image: docker.io/library/caddy:2.11.2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped
    depends_on:
      - concord 
    
volumes:
  concord-data: {}
  concord-yarn: {}
  caddy-data: {}
  caddy-config: {}
